# The $Timer parameter is required for the function to recognize the Time Trigger
param($Timer)

# --- Configuration (Pulled from App Settings) ---
$AzureKeyVaultName = $env:VaultName
$SendGridApiKey    = $env:SendGridApiKey
$RawFromEmail      = $env:FromEmail

# -- Fix: Parse "From" Address to separate Name and Email --
if ($RawFromEmail -match '^(?:"?)(.*?)(?:"?)\s*<(.*)>$') {
    $FromName  = $matches[1].Trim()
    $FromEmail = $matches[2].Trim()
}
else {
    $FromName  = "CloudOps Automation" 
    $FromEmail = $RawFromEmail.Trim()
}

# -- Multiple Recipient Handling --
function Get-EmailList {
    param ($EmailString)
    if ([string]::IsNullOrWhiteSpace($EmailString)) { return @() }
    return $EmailString -split ',' | ForEach-Object { $_.Trim() } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
}

$ToList  = Get-EmailList -EmailString $env:ToEmailList
$BccList = Get-EmailList -EmailString $env:BccEmailList

# --- Validation ---
if ([string]::IsNullOrWhiteSpace($AzureKeyVaultName) -or [string]::IsNullOrWhiteSpace($SendGridApiKey)) {
    Write-Error "Missing App Settings. Ensure KEY_VAULT_NAME and SENDGRID_API_KEY are set."
    return
}
if ($ToList.Count -eq 0) {
    Write-Error "Missing App Settings. Ensure TO_EMAIL is set."
    return
}

# --- Constants ---
# Logic: Critical includes day 7. Error is anything above 7 up to 15.
$CriticalThreshold = 7  
$ErrorThreshold    = 15
$WarningThreshold  = 30

# --- HTML Style (CSS) ---
$HtmlStyle = @"
<style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }
    h2 { color: #333; }
    table { border-collapse: collapse; width: 100%; border: 1px solid #ddd; }
    th { background-color: #0078D4; color: white; text-align: left; padding: 12px; }
    td { border: 1px solid #ddd; padding: 10px; }
    tr:nth-child(even) { background-color: #f9f9f9; }
    .footer { font-size: 12px; color: #666; margin-top: 20px; border-top: 1px solid #ccc; padding-top: 10px;}
</style>
"@

# --- Helper Function: Send-SendGridEmail ---
function Send-SendGridEmail {
    param (
        [string]$Subject,
        [string]$HtmlContent,
        [bool]$HighPriority = $false
    )

    $Headers = @{
        "Authorization" = "Bearer $SendGridApiKey"
        "Content-Type"  = "application/json"
    }

    # Force Arrays for To/Bcc (SendGrid requirement)
    $ToObjects = @($ToList | ForEach-Object { @{ email = $_ } })

    $PersonalizationBlock = @{
        to = $ToObjects
        subject = $Subject
    }

    if ($BccList.Count -gt 0) {
        $BccObjects = @($BccList | ForEach-Object { @{ email = $_ } })
        $PersonalizationBlock["bcc"] = $BccObjects
    }

    # Separate 'email' and 'name' in the From block
    $JsonPayload = @{
        personalizations = @( $PersonalizationBlock )
        from = @{ 
            email = $FromEmail
            name  = $FromName
        }
        content = @(
            @{
                type = "text/html"
                value = $HtmlContent
            }
        )
    }

    if ($HighPriority) {
        $JsonPayload.Add("headers", @{
            "X-Priority" = "1"
            "Importance" = "high"
            "Priority"   = "Urgent"
        })
    }

    $BodyJson = $JsonPayload | ConvertTo-Json -Depth 10

    try {
        Invoke-RestMethod -Uri "https://api.sendgrid.com/v3/mail/send" -Method Post -Headers $Headers -Body $BodyJson
        Write-Host "Email sent: $Subject" -ForegroundColor Green
    }
    catch {
        Write-Warning "JSON Payload attempted: $BodyJson"
        Write-Error "Failed to send email. Error: $_"
    }
}

# --- Helper to Build HTML Body ---
function Build-HtmlBody {
    param ($Title, $DataList)
    $TableFragment = $DataList | ConvertTo-Html -Fragment | Out-String
    return "$HtmlStyle <h2>$Title</h2> $TableFragment <div class='footer'>Report generated by CloudOps Automation</div>"
}

# --- Main Logic ---

Write-Host "Azure Function Triggered. Starting Certificate Check..."

# 1. Authenticate
if (-not (Get-AzContext)) { 
    Write-Host "Context not found. Attempting to connect via Managed Identity..."
    try {
        Connect-AzAccount -Identity -ErrorAction Stop
    }
    catch {
        Write-Error "Failed to login with Managed Identity. Ensure System Assigned Identity is enabled and has Key Vault permissions."
        return
    }
}

# 2. Get Certificates
Write-Host "Fetching certificates from Vault: $AzureKeyVaultName..."
try {
    $AllCerts = Get-AzKeyVaultCertificate -VaultName $AzureKeyVaultName -ErrorAction Stop
}
catch {
    Write-Error "Could not find Key Vault '$AzureKeyVaultName' or access is denied. Error: $_"
    return
}

# 3. Categorize Certificates
$CriticalList = @()
$ErrorList    = @()
$WarningList  = @()
$Now          = Get-Date

foreach ($Cert in $AllCerts) {
    if ($null -ne $Cert.Expires) {
        $DaysLeft = ($Cert.Expires - $Now).Days
        
        $CertObj = [PSCustomObject]@{
            "Certificate Name" = $Cert.Name
            "Expiry Date"      = $Cert.Expires.ToString("yyyy-MM-dd HH:mm")
            "Days Remaining"   = $DaysLeft
        }

        # UPDATED LOGIC: Changed -lt to -le to include exactly 7 days
        if ($DaysLeft -le $CriticalThreshold) {
            $CriticalList += $CertObj
        }
        elseif ($DaysLeft -lt $ErrorThreshold) {
            $ErrorList += $CertObj
        }
        elseif ($DaysLeft -lt $WarningThreshold) {
            $WarningList += $CertObj
        }
    }
}

# 4. Trigger Emails

# -- Critical (<= 7 Days) --
if ($CriticalList.Count -gt 0) {
    Write-Host "Sending Critical Alert (<= 7 Days)..."
    # Updated Title to reflect "Less than or Equal to"
    $Body = Build-HtmlBody -Title "CRITICAL: Certificates Expiring in <= $CriticalThreshold Days" -DataList $CriticalList
    Send-SendGridEmail -Subject "CRITICAL: Azure Key Vault Certificates Expiring Soon (<= 7 Days)" -HtmlContent $Body -HighPriority $true
}

# -- Error (< 15 Days) --
if ($ErrorList.Count -gt 0) {
    Write-Host "Sending Error Alert..."
    $Body = Build-HtmlBody -Title "ERROR: Certificates Expiring in < $ErrorThreshold Days" -DataList $ErrorList
    Send-SendGridEmail -Subject "Error: Azure Key Vault Certificates Expiring Soon" -HtmlContent $Body
}

# -- Warning (< 30 Days) --
if ($WarningList.Count -gt 0) {
    Write-Host "Sending Warning Alert..."
    $Body = Build-HtmlBody -Title "WARNING: Certificates Expiring in < $WarningThreshold Days" -DataList $WarningList
    Send-SendGridEmail -Subject "Warning: Azure Key Vault Certificates Expiring Soon" -HtmlContent $Body
}

Write-Host "Function execution completed."
